### ISSUE TITLE
✅ ENV: 누락된 환경설정

### ISSUE THREAD

**Issue by otterp012** [over-ui/unstyled#18]
## Description
현재, 패키지 root에 eslint, prettier 관련 설정파일이 누락되어 
eslint, prettier 관련 환경설정을 추가합니다. 또 이전에 설정해 놓았던 `github actions`에 `lint`를 자동으로 수행하도록 변경해야합니다.

## TO-DO

- [x]  eslint 관련 설정
- [x]  prettier 관련 설정
- [x]  github actions 수정

### ETC
- lint 설정을 키고 끄는 부분에 대한 협의 필요
