### ISSUE TITLE
✅ FEATURE: Dialog

### ISSUE THREAD

**Issue by lv0314** [over-ui/unstyled#40]
## Description
일반적인 모달 컴포넌트입니다.
트리거를 눌렀을 시 모달이 열리며, 모달의 외부를 클릭하거나, 포커스를 모달 밖으로 옮기거나, esc키를 눌렀을 경우 모달이 닫힙니다.
overlay를 통해 모달 밖의 영역에 스타일을 입힐 수 있습니다.

## TO-DO

- [x] modal, non-modal 모드 지원(필요성 고민 중)
- [x] 모달이 열릴 때 첫 번째 focusable 요소에 오토포커스, 해제될 때 trigger에 오토포커스
- [x] Esc 키로 모달 닫기
- [x] controllable state로 구현하기
